service: spark-mentor-predeploy

plugins:
  - serverless-cloudformation-sub-variables

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1 

custom:
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    ACEAIBotBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '#{AWS::AccountId}-spark-mentor-chatbot-bucket-${self:custom.stage}'